"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from datetime import timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&f6sx^2e!*x1(mdo$#k6fu#@12%1rb4x9^3fw1n9znhk0du#1_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'saas_system',
        'USER': 'saas_admin',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
        'TEST': {
            'name': 'mytestdb',
        }
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'app.features.userprofile.authenticate.CustomAuthentication',
    ),
}

# allow any url
# CORS_ORIGIN_ALLOW_ALL = True
# specfically allow the react url
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
]

# CSRF settings (if needed)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4200",
]

#https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html#settings
# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
#     "ROTATE_REFRESH_TOKENS": True,
#     "BLACKLIST_AFTER_ROTATION": True,
#     "ALGORITHM": "HS256",  # Using HS256
#     # The algorithm used to sign/verify the token if used need SIGNING_KEY and VERIFYING_KEY
#     # "ALGORITHM": "RS256",
#     # "SIGNING_KEY": open(os.path.join(BASE_DIR, 'path/to/private.pem')).read(),
#     # "VERIFYING_KEY": open(os.path.join(BASE_DIR, 'path/to/public.pem')).read(),
#     "AUTH_HEADER_TYPES": ("Bearer",),
# }

SIMPLE_JWT = {
  'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1),
  'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
  'ROTATE_REFRESH_TOKENS': False,
  'BLACKLIST_AFTER_ROTATION': True,
  'UPDATE_LAST_LOGIN': False,

  'ALGORITHM': 'HS256',
  'SIGNING_KEY': SECRET_KEY,
  'VERIFYING_KEY': None,
  'AUDIENCE': None,
  'ISSUER': None,

  'AUTH_HEADER_TYPES': ('Bearer',),
  'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
  'USER_ID_FIELD': 'id',
  'USER_ID_CLAIM': 'user_id',
  'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

  'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
  'TOKEN_TYPE_CLAIM': 'token_type',

  'JTI_CLAIM': 'jti',

  'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
  'SLIDING_TOKEN_LIFETIME': timedelta(minutes=1),
  'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),

  # Custom settings for handling refresh tokens via cookies
  'AUTH_REFRESH_COOKIE': 'refresh_token',
  'AUTH_REFRESH_COOKIE_PATH': '/',
  'AUTH_REFRESH_COOKIE_SECURE': False,  # Set to True in production
  'AUTH_REFRESH_COOKIE_HTTP_ONLY': True,
  'AUTH_REFRESH_COOKIE_SAMESITE': 'Lax',  # Changed from 'None' to 'Lax' for development
  
#   'AUTH_REFRESH_COOKIE': 'refresh_token',      # Cookie name for refresh token
#   'AUTH_REFRESH_COOKIE_DOMAIN': None,         # Domain for the cookie
#   'AUTH_REFRESH_COOKIE_SECURE': False,        # Set to True in production
#   'AUTH_REFRESH_COOKIE_HTTP_ONLY': True,      # Prevents JavaScript access
#   'AUTH_REFRESH_COOKIE_PATH': '/',            # Path for the cookie
#   'AUTH_REFRESH_COOKIE_SAMESITE': 'None', 
}

IMAGE_PATH_CLOUDINARY = "https://res.cloudinary.com/dblq0iusj/image/upload/v1730376611/"

# Add these new CORS settings
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']