# Generated by Django 5.0 on 2024-06-30 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.operator",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.operator",
            ),
        ),
    ]
