# Generated by Django 5.0 on 2024-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("function_key", models.CharField(max_length=80)),
            ],
        ),
    ]
