# Generated by Django 5.0 on 2024-06-30 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_functionrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermissionRoleFunctionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.functionrule",
                    ),
                ),
                (
                    "permission_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.permissionrole",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="permissionrole",
            name="function_rules",
            field=models.ManyToManyField(
                through="app.PermissionRoleFunctionRule",
                to="app.functionrule",
                verbose_name="function rule",
            ),
        ),
    ]
