# Generated by Django 5.0 on 2024-07-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_permissionrole_permissionrolefunctionrule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="permission_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.permissionrole",
            ),
        ),
    ]
