# Generated by Django 5.0 on 2024-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userprofile_permission_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
