# Generated by Django 5.0 on 2024-07-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_supplier_contact_name_supplier_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=80)),
                ('product_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=180, null=True)),
                ('measure_unit', models.CharField(blank=True, max_length=80, null=True)),
                ('weight', models.CharField(blank=True, max_length=80, null=True)),
                ('length', models.CharField(blank=True, max_length=80, null=True)),
                ('width', models.CharField(blank=True, max_length=80, null=True)),
                ('height', models.CharField(blank=True, max_length=80, null=True)),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.supplier')),
            ],
        ),
    ]
