# Generated by Django 5.0 on 2024-07-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
