# Generated by Django 5.0 on 2024-07-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimension_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
