# Generated by Django 5.0 on 2024-08-04 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('in_stock', models.CharField(max_length=80)),
                ('on_order', models.CharField(max_length=80)),
                ('reserved', models.CharField(max_length=80)),
                ('min_stock', models.CharField(max_length=80)),
                ('max_stock', models.CharField(max_length=80)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.operator')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.store')),
            ],
        ),
    ]
