# Generated by Django 5.0 on 2024-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='in_stock',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='max_stock',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='min_stock',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='on_order',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reserved',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
