# Generated by Django 5.0 on 2024-08-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reached',
            field=models.BooleanField(default=False),
        ),
    ]
