# Generated by Django 5.0 on 2024-08-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_purchaseorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
