# Generated by Django 5.0 on 2024-09-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_balancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.balance'),
        ),
    ]
