# Generated by Django 5.0 on 2024-09-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_purchaseorder_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
    ]
