# Generated by Django 5.0 on 2024-09-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_purchaseitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='name',
            new_name='code',
        ),
    ]
