# Generated by Django 5.0 on 2024-09-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.customer'),
        ),
    ]
