# Generated by Django 5.0 on 2024-10-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_purchaseorder_customer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_product_store',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'store', 'supplier')},
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('product', 'store', 'supplier'), name='unique_product_store_supplier'),
        ),
    ]
