# Generated by Django 5.0 on 2024-10-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_inventory_unique_product_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='code',
        ),
    ]
