# Generated by Django 5.0 on 2024-10-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_inventory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='total_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
