# Generated by Django 5.0 on 2024-10-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_store_total_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='in_stock',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
    ]
