# Generated by Django 5.0 on 2024-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_inventory_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='max_stock',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='min_stock',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='on_order',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reserved',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
    ]
