# Generated by Django 5.0 on 2024-10-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_alter_inventory_max_stock_alter_inventory_min_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
