# Generated by Django 5.0 on 2024-11-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_salesorder_salesitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Delivery", "Delivery"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
