# Generated by Django 5.0 on 2024-11-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_alter_salesorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Completed", "Completed")],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
