# Generated by Django 5.0 on 2024-11-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("Bike", "Bike"), ("Car", "Car"), ("Van", "Van")],
                        max_length=50,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
