# Generated by Django 5.0 on 2024-11-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_courier"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="default_delivery_cost",
            field=models.IntegerField(default=0),
        ),
    ]
