# Generated by Django 5.0 on 2024-11-17 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_courier_default_delivery_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrderDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("delivery_cost", models.IntegerField(default=0)),
                ("is_free_delivery", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.courier"
                    ),
                ),
                (
                    "sales_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery",
                        to="app.salesorder",
                    ),
                ),
            ],
        ),
    ]
