# Generated by Django 5.0 on 2024-11-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_salesorderdelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("share_percentage", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
