# Generated by Django 5.0 on 2024-11-19 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ADD", "Add"),
                            ("MINUS", "Minus"),
                            ("NEW_PRODUCT", "New Product"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "action_date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "auto_generated_note",
                    models.CharField(
                        choices=[
                            ("NEW_PURCHASE_ORDER", "New Purchase Order"),
                            ("NEW_SALES_ORDER", "New Sales Order"),
                            ("INCREASE_UPDATE_STOCK", "Increase Update Stock"),
                            ("DECREASE_UPDATE_STOCK", "Decrease Update Stock"),
                        ],
                        max_length=400,
                    ),
                ),
                ("stock", models.IntegerField(blank=True, max_length=80, null=True)),
                (
                    "stock_before_action",
                    models.IntegerField(blank=True, max_length=80, null=True),
                ),
                (
                    "stock_after_action",
                    models.IntegerField(blank=True, max_length=80, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.store",
                    ),
                ),
                (
                    "userprofile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="inventorylog",
            constraint=models.UniqueConstraint(
                fields=("product", "store"), name="unique_product_store_log"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventorylog", unique_together={("product", "store")},
        ),
    ]
