# Generated by Django 5.0 on 2024-11-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_inventorylog_inventorylog_unique_product_store_log_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylog",
            name="auto_generated_note",
            field=models.CharField(
                choices=[
                    ("NEW_PURCHASE_ORDER", "New Purchase Order"),
                    ("NEW_SALES_ORDER", "New Sales Order"),
                    ("INCREASE_UPDATE_STOCK", "Increase Update Stock"),
                    ("DECREASE_UPDATE_STOCK", "Decrease Update Stock"),
                    ("NEW_PRODUCT", "New Product"),
                ],
                max_length=400,
            ),
        ),
    ]
