# Generated by Django 5.0 on 2024-11-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_inventory_in_stock_alter_inventory_max_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='in_stock',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='max_stock',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='min_stock',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='on_order',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reserved',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
    ]
