# Generated by Django 5.0 on 2024-11-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_inventory_in_stock_alter_inventory_max_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client'),
        ),
    ]
