# Generated by Django 5.0 on 2024-11-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_alter_inventorylog_auto_generated_note_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventorylog", name="unique_product_store_log",
        ),
        migrations.AlterUniqueTogether(name="inventorylog", unique_together=set(),),
    ]
