# Generated by Django 5.0 on 2024-11-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_salesorder_status'),
        ('app', '0055_remove_inventorylog_unique_product_store_log_and_more'),
    ]

    operations = [
    ]
