# Generated by Django 5.0 on 2024-12-09 03:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_clientbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('action', models.CharField(blank=True, choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], max_length=100, null=True)),
                ('transfer_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.balance')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.operator')),
            ],
        ),
    ]
