# Generated by Django 5.0 on 2024-12-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_balancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehistory',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
