# Generated by Django 5.0 on 2024-12-13 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_balancehistory_note'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_product_store_supplier',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'store')},
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.supplier'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('product', 'store'), name='unique_product_store'),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
    ]
