# Generated by Django 5.0 on 2024-12-19 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='MYR', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.supplier'),
        ),
        migrations.AddField(
            model_name='income',
            name='attachment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(default='MYR', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.customer'),
        ),
    ]
