# Generated by Django 5.0 on 2024-12-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.PROTECT, to='app.customer'),
            preserve_default=False,
        ),
    ]
