# Generated by Django 5.0 on 2024-12-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_invoice_currency_alter_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='location',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.PROTECT, to='app.location'),
            preserve_default=False,
        ),
    ]
