# Generated by Django 5.0 on 2024-12-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='income',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
    ]
