# Generated by Django 5.0 on 2024-12-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_expense_created_at_income_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
