# Generated by Django 5.0 on 2024-12-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_purchaseorder_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
