# Generated by Django 5.0 on 2024-12-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_salesorder_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='income',
            name='created_at',
        ),
    ]
