# Generated by Django 5.0 on 2024-12-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_remove_expense_created_at_remove_income_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
