# Generated by Django 5.0 on 2024-12-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_alter_salesorder_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
